### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by Topher05** [Topher05/Scrum-and-Github-Flow#1]
**User Story**
As a student, I often lose the papers with the grades on them and forget to calculate how I am doing so far so it would be great if I could see all of those in one place.

-  Persona: Student who wants to view grades and who loses papers.
- Feature: students are able to view grades
- business value: Student will be able to view grade and have a better idea of how they are doing in a class

**Task List**

- [x] check that the database will be able to display grades
- [ ] Create Html for students to view grades
- [ ] Connect to the backend
- [ ] connect backend to database

**Acceptance Criteria** 

Only one semester
Works in browser
